server:
    port: 8081

spring:
    datasource:
        url: jdbc:mysql://${dbhost}:${dbport}/nofluffcars_data
        username: root
        password: root
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
        show-sql: true
security:
    sign-secret: secret
    token-lifetime: 600000 # 10min - 10 * 60 * 1000ms